# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://19.15.14.82:15343/gpziplatform?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: xt_ztk
    password: 7d%q,{cw
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8090

logging:
  level:
    com.gpzi.gpplatform: debug
    org.springframework: warn
  config: classpath:logback.xml